replicaCount: 2

image:
  repository: nitzanm594/commit
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port:  80
  targetPort: 80
  nodePort: 30082

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi